Net-Core-Identity-App/ViewModels/PasswordChangeViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Net_Core_Identity_App.ViewModels
{
    public class PasswordChangeViewModel
    {
        [Display(Name = "Eski şifreniz")]
        [Required(ErrorMessage = "Eski şifreniz gereklidir")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Şifreniz en az 4 karakterli olmak zorundadır.")]
        public string PasswordOld { get; set; }

        [Display(Name = "Yeni şifreniz")]
        [Required(ErrorMessage = "Yeni şifreniz gereklidir")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Şifreniz en az 4 karakterli olmak zorundadır.")]
        public string PasswordNew { get; set; }

        [Display(Name = "Onay yeni şifreniz")]
        [Required(ErrorMessage = "Onay yeni şifre gereklidir")]
        [DataType(DataType.Password)]
        [MinLength(4, ErrorMessage = "Şifreniz en az 4 karakterli olmak zorundadır.")]
        [Compare("PasswordNew", ErrorMessage = "Yeni şifreniz  ve onay şifreniz birbirinden farklıdır.")]
        public string PasswordConfirm { get; set; }
    }
}

Net-Core-Identity-App/Controllers/MemberController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Net_Core_Identity_App.Models;
using Net_Core_Identity_App.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mapster;
using Microsoft.AspNetCore.Mvc.Rendering;
using Net_Core_Identity_App.Enums;
using Microsoft.AspNetCore.Http;
using System.IO;
using System.Security.Claims;

namespace Net_Core_Identity_App.Controllers
{
    [Authorize] // yetkisiz girisi yasakladik. cookie olmadan asla. sadece uyeler girebilir.
    public class MemberController : BaseController
    {

        public MemberController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager):base(userManager,signInManager)
        {
    
        }


        public IActionResult Index()
        {
            AppUser user = CurrentUser; // uyeyi buluyor ve getiriyoruz. Base controller yardimiyla.

            // UserViewModel userViewModel = new UserViewModel(); // user bilgilerini modele gore aliyoruz. 
            // userViewModel.UserName = user.UserName;

            // yukaridaki kod fazlaligi. bunun olmamasi icin mapster kutuphanesini kullaniyoruz. mapster AppUser modelden UserViewModel'e otomatik donus saglayacak. 
            UserViewModel userViewModel = user.Adapt<UserViewModel>();

            return View(userViewModel); // userViewModel dolmus olarak geldi. bunu view'e gonderiyoruz.
        }

        public IActionResult UserEdit()
        {
            AppUser user = CurrentUser; // kullaniciyi elde ediyoruz. name ile buluyoruz. user identity kesin gelir cunku bu sinif login olanlarin girebilecegi authorize ayarlanmis bir sinif. base controller yardimiyla

            UserViewModel userViewModel = user.Adapt<UserViewModel>(); // // elde ettigimiz user'i cast ediyoruz. daha once olusturdugumuz userview modele cast ediyoruz. yani o modeldeki property alanlarini degistirebilir sadece. 

            ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));

            return View(userViewModel); // view'e dolu bir userViewModel'i veriyoruz. 
        }

        [HttpPost]
        public async Task<IActionResult> UserEdit(UserViewModel userViewModel, IFormFile userPicture) // UserEdit.cshtml sayfasindan userViewModel gelecek. ayrica sayfadan userPicture'i da aldik.
        {
           ModelState.Remove("Password"); // password alani kullanmadigimiz icin kaldirmamiz gerekir. yoksa asagidaki valid'e takilir.
           ViewBag.Gender = new SelectList(Enum.GetNames(typeof(Gender)));

            if (ModelState.IsValid) // gelen bilgiler validse
            {
                AppUser user = CurrentUser; // base controller yardimiyla.


                if (userPicture != null && userPicture.Length > 0) // user picture bos degil ve dolu ise
                {
                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(userPicture.FileName); // Guid.NewGuid().ToString() rastgele bi' isim olusturuyor. Path.GetExtension(userPicture.FileName) sonuna dosya uzantisini ekliyor. 15asd15as1d5.png gibi. 

                    var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/UserPicture", fileName); // resmi kayit edecegimiz yer. 

                    using (var stream = new FileStream(path, FileMode.Create)) // FileMode.Create, path bossa olustur demek. 
                    {
                        await userPicture.CopyToAsync(stream); // kayit yoluna resmi kopyaliyoruz. 

                        user.Picture = "/UserPicture/" + fileName; // veritabanina kayit yolu kaydedildi. 
                    }
                }


                user.UserName = userViewModel.UserName;
                user.Email = userViewModel.Email;
                user.PhoneNumber = userViewModel.PhoneNumber;
                user.City = userViewModel.City;

                user.BirthDay = userViewModel.BirthDay;

                user.Gender = (int)userViewModel.Gender; // database'de int oldugu icin enum'in int'e cast edilmesi lazim. 

                IdentityResult result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    await userManager.UpdateSecurityStampAsync(user);
                    await signInManager.SignOutAsync();
                    await signInManager.SignInAsync(user, true);

                    ViewBag.success = "true"; // flag
                }
                else
                {
                    AddModelError(result);
                }
            }

            return View(userViewModel); // view'e tekrar gonderiyoruz. gondermezsek kullanici hata alirsa textbox icleri bos olur. 
        }

        public IActionResult PasswordChange()
        {
            return View();
        }

        [HttpPost]
        public IActionResult PasswordChange(PasswordChangeViewModel passwordChangeViewModel)
        {
            if (ModelState.IsValid) // view'de girilen model validasyonu gecerliyse, dogruysa
            {
                AppUser user = CurrentUser; // name degerini o anki cookie bilgisinden okuyor. veritabanindan gelmiyor. async olmadan direk result'tan gidildi. base controller yardimiyla.

                bool exist = userManager.CheckPasswordAsync(user, passwordChangeViewModel.PasswordOld).Result; // girilen eski sifrenin dogrulugu kontrol ediliyor. 

                if (exist)
                {
                    IdentityResult result = userManager.ChangePasswordAsync(user, passwordChangeViewModel.PasswordOld, passwordChangeViewModel.PasswordNew).Result; // sifre degistirme islemi yapiliyor. 

                    if (result.Succeeded) // eger basariyla sifre degismisse 
                    {
                        userManager.UpdateSecurityStampAsync(user); // SecurityStamp guncelle. 
                        // eger asagidaki iki parcayi girmeseydik identity api otomatik 30 dakika sonra oturumu sonlandiracakti, login sayfasina yonlendirecekti.  bu varsayilan bi' ayardi. biz hemen cikis ve giris yaptik. 
                        signInManager.SignOutAsync(); // sifre degistigi icin cikis islemi yapiliyor. 
                        signInManager.PasswordSignInAsync(user, passwordChangeViewModel.PasswordNew, true, false); // kullanici giris islemi saglaniyor. true ise cookie'nin startup.cs de belirlenen gecerlilik suresi aktif ediliyor. false ile kilitleme islemi deaktif. 

                        // ornegin hem kullanici hem bayi login ekranlari varsa bunlarin secimi icin signInManager.SignInAsync() method kullanilir. (ekstra durum)

                        ViewBag.success = "true"; // flag atiliyor. 
                    }
                    else
                    {
                        AddModelError(result);
                    }
                }
                else // eski sifrenin yanlis olma durumu.  exist'e gore. 
                {
                    ModelState.AddModelError("", "Eski şifreniz yanlış");
                }
            }

            return View(passwordChangeViewModel); // hatalar varsa hatalari tekrar gosterebilmek icin kullaniciya gonderiyoruz. ilgili alanlar textboxlar tekrar dolsun. 
        }

        public void LogOut()
        {
            signInManager.SignOutAsync();
        }

        // https://localhost:44313/Member/AccessDenied?ReturnUrl=%2FMember%2FViolencePage
        public IActionResult AccessDenied(string ReturnUrl) // opts.AccessDeniedPath = new PathString("/Member/AccessDenied"); startup.cs 'den geliyor. 
        {
            if (ReturnUrl.ToLower().Contains("ViolencePage"))
            {
                ViewBag.message = "Erişmeye çalıştığınız sayfa şiddet bazlı video içerdiğinden dolayı 15 yaşında büyük olmanız gerekmektedir";
            }
            else if (ReturnUrl.ToLower().Contains("AnkaraPage"))
            {
                ViewBag.message = "Only Angara";
            }
            else if (ReturnUrl.ToLower().Contains("exchange"))
            {
                ViewBag.message = "30 günlük ücretsiz deneme hakkınız sona ermiştir.";
            }
            else
            {
                ViewBag.message = "Bu sayfaya erişim izniniz yoktur. Erişim izni almak için site yöneticisiyle iletişime geçiniz.";
            }

            return View();
        }

        [Authorize(Roles = "Manager,Admin")]
        public IActionResult Manager()
        {
            return View();
        }

        [Authorize(Roles = "Editor,Admin")] // editor ve admin disindaki uyeler ===> opts.AccessDeniedPath = new PathString("/Member/AccessDenied"); // uye kullanici yetkisiz oldugu sayfaya girmeye calistiginda buradaki path'e yonlendirilip, bilgilendirilecek.
        public IActionResult Editor()
        {
            return View();
        }


        [Authorize(Policy = "AnkaraPolicy")]
        public IActionResult AnkaraPage()
        {
            return View();
        }

        [Authorize(Policy = "ViolencePolicy")]
        public IActionResult ViolencePage()
        {
            return View();
        }

        public async Task<IActionResult> ExchangeRedirect() // IActionResult Exchange() sayfasina yonlendirilecek.
        {
            bool result = User.HasClaim(x => x.Type == "ExpireDateExchange"); // kullanicida belirttigimiz claim var mi?

            if (!result)
            {
                // AspNetUserClaims tablosuna ClaimType'i ExpireDateExchange olan, ClaimValue'su ise su andaki tarihten 30 gun sonrasi olan deger tutacagiz.

                Claim ExpireDateExchange = new Claim("ExpireDateExchange", DateTime.Now.AddDays(30).Date.ToShortDateString(), ClaimValueTypes.String, "Internal");

                await userManager.AddClaimAsync(CurrentUser, ExpireDateExchange); // claims kullaniciya ekleniyor. 

                // cookie guncel kalmas icin giris ve cikis islemi.
                await signInManager.SignOutAsync();

Net-Core-Identity-App/Views/Member/AccessDenied.cshtml
@{
    ViewData["Title"] = "AccessDenied";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<div class="alert alert-danger">
    @ViewBag.message
</div>

Net-Core-Identity-App/Views/Member/AnkaraPage.cshtml
@{
    ViewData["Title"] = "AnkaraPage";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Welcome to Ankara Page</h1>

Net-Core-Identity-App/Views/Member/Editor.cshtml
@{
    ViewData["Title"] = "Editor";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Welcome Editor's Page</h1>

Net-Core-Identity-App/Views/Member/Exchange.cshtml
@{
    ViewData["Title"] = "Exchange";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h3>30 gün boyunca ücretsiz olarak bu sayfayı görebilirsiniz.</h3>

Net-Core-Identity-App/Views/Member/Index.cshtml
@model UserViewModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}


<h3 class="text-center">Kullanıcı Bilgileri</h3>
<div class="row">

    <div class="col-sm-3">
        <img style="width:100%; height:100%" src="@Model.Picture" />
    </div>

    <div class="col-sm-9">

        <table class="table table-bordered table-striped">
            <tr>
                <th>Kullanıcı</th>
                <td>@Model.UserName</td>
            </tr>
            <tr>
                <th>E-posta</th>
                <td>@Model.Email</td>
            </tr>

            <tr>
                <th>Telefon</th>
                <td>@Model.PhoneNumber</td>
            </tr>

            <tr>
                <th>Şehir</th>
                <td>
                    @if (!String.IsNullOrEmpty(Model.City))
                    {
                        @Model.City
                    }
                    else

                    {
                        <span>Belirtilmemiş</span>
                    }
                </td>
            </tr>
            <tr>
                <th>Doğum tarihi</th>
                <td>
                    @if (Model.BirthDay != null)
                    {
                        @Model.BirthDay?.ToShortDateString() @*Eger birthday null gelmezse ToShortDateString() fonk. calisacak.*@
                    }
                    else

                    {
                        <span>Belirtilmemiş</span>
                    }
                </td> 
            </tr>

            <tr>
                <th>Cinsiyet</th>
                <td>@Model.Gender</td>
            </tr>

        </table>

    </div>
</div>

Net-Core-Identity-App/Views/Member/Manager.cshtml
@{
    ViewData["Title"] = "Manager";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Welcome Manager's Page</h1>

Net-Core-Identity-App/Views/Member/PasswordChange.cshtml
@model Net_Core_Identity_App.ViewModels.PasswordChangeViewModel

@{
    ViewData["Title"] = "PasswordChange";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h2>Şifre Değiştirme</h2>
<hr />

@if (ViewBag.success == "true")
{
    <div class="alert alert-info">
        Şifreniz Güncellenmiştir.
    </div>
}
else
{
<div class="row">
    <div class="col-md-4">
        <form asp-action="PasswordChange">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="PasswordOld" class="control-label"></label>
                <input asp-for="PasswordOld" class="form-control" />
                <span asp-validation-for="PasswordOld" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordNew" class="control-label"></label>
                <input asp-for="PasswordNew" class="form-control" />
                <span asp-validation-for="PasswordNew" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PasswordConfirm" class="control-label"></label>
                <input asp-for="PasswordConfirm" class="form-control" />
                <span asp-validation-for="PasswordConfirm" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Şifre Değiştir" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
}

Net-Core-Identity-App/Views/Member/UserEdit.cshtml
@model Net_Core_Identity_App.ViewModels.UserViewModel

@{
    ViewData["Title"] = "UserEdit";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}


<h2>Bilgi Güncelleme</h2>
@if (ViewBag.success == "true")
{
    <div class="alert alert-info">
        <span>Bilgileriniz güncellenmiştir.</span>
    </div>
}
<div class="row">
    <div class="col-md-12">
        <form asp-action="UserEdit" method="post" enctype="multipart/form-data"> @*hem post ile bilgiler hemde resim yuklenmesi multipart.*@
            <div asp-validation-summary="ModelOnly" class="text-danger"></div> @*asp-validation-summary modelden gelen hatalari gosterecek.*@
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="BirthDay" class="control-label"></label>
                <input asp-for="BirthDay" class="form-control" />
                <span asp-validation-for="BirthDay" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select class="form-control" asp-for="Gender" asp-items="@ViewBag.Gender"></select>
            </div>

            <div class="form-group">

                <label class="control-label">Resim</label>
                <input class="form-control" type="file" name="userPicture" />
            </div>

            <div class="form-group">
                <input type="submit" value="Güncelle" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Net-Core-Identity-App/Views/Member/ViolencePage.cshtml
@{
    ViewData["Title"] = "ViolencePage";
    Layout = "~/Views/Member/_MemberLayout.cshtml";
}

<h1>Violence Video</h1>

<iframe width="600" height="338" src="https://www.youtube.com/embed/X55jQYKyDFE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

Net-Core-Identity-App/Views/Member/_MemberLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Net_Core_Identity_App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Net Core Identity App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Member" asp-action="Index">Üye Panel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Index" asp-controller="Admin">Admin Panel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Editor" asp-controller="Member">Editor Panel</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-action="Manager" asp-controller="Member">Manager Panel</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>


    <div class="container" style="margin-top:10px;">
        <div class="row">
            <div class="col-md-8">
                @RenderBody()
            </div>
            <div class="col-md-4">
                <h3>Menü</h3>

                <a class="btn btn-danger btn-block" asp-action="AnkaraPage" asp-controller="Member">Ankara Page</a>

                <a class="btn btn-danger btn-block" asp-action="ViolencePage" asp-controller="Member">Violence Video</a>

                <a class="btn btn-danger btn-block" asp-action="ExchangeRedirect" asp-controller="Member">Borsa Bilgileri</a>

                <a class="btn btn-info btn-block" asp-action="PasswordChange" asp-controller="Member">Şifre değiştirme</a>

                <a class="btn btn-info btn-block" asp-action="UserEdit" asp-controller="Member">Bilgi güncelleme</a>

                <a class="btn btn-info btn-block" asp-action="Logout" asp-controller="Member" asp-route-returnUrl="/Home/Index">Çıkış yap</a> @*return url cikis yapilinca gidecegi yer.*@
            </div>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Net Core Identity App - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>